/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import istin.Autor;
import istin.Login;
import istin.Cliente;
import javax.swing.JOptionPane;

/**
 *
 * @author anasofia
 */
public class TelaNovaConta extends javax.swing.JFrame {

    private Login login;
    
    public TelaNovaConta() {
        initComponents();
        
        login = Login.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        btCriar = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        lbUsername = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbSenha = new javax.swing.JLabel();
        btVoltar = new javax.swing.JButton();
        rbtCliente = new javax.swing.JRadioButton();
        rbtAutor = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btCriar.setText("Criar Conta");
        btCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCriarActionPerformed(evt);
            }
        });
        getContentPane().add(btCriar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, -1, -1));
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 110, -1));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 170, -1));
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 170, -1));

        lbUsername.setText("Username:");
        getContentPane().add(lbUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        lbEmail.setText("Email:");
        getContentPane().add(lbEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        lbSenha.setText("Senha:");
        getContentPane().add(lbSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        btVoltar.setText("<");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        buttonGroup.add(rbtCliente);
        rbtCliente.setText("Cliente");
        rbtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtClienteActionPerformed(evt);
            }
        });
        getContentPane().add(rbtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        buttonGroup.add(rbtAutor);
        rbtAutor.setText("Autor");
        getContentPane().add(rbtAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCriarActionPerformed
        
        String nome = txtUsername.getText();
        String email = txtEmail.getText();
        String senha = txtSenha.getText();
        
        if(nome.equals("") || email.equals("") || senha.equals("")) {
            txtUsername.setText("");
            txtEmail.setText("");
            txtSenha.setText("");
            txtUsername.requestFocus();
            
            JOptionPane.showMessageDialog(null, "Todos os campos de cadastro devem estar preenchidos");
            
        } else if(!rbtAutor.isSelected() && !rbtCliente.isSelected()) {
            JOptionPane.showMessageDialog(null, "Selecione o tipo de conta");
        }else {
            if(rbtCliente.isSelected()){
                Cliente novoCliente = new Cliente(0, nome, email, senha, null);
                login.criaNovaConta(novoCliente);
            } else {
                Autor novoAutor = new Autor(nome, email, senha, null);
                login.criaNovaConta(novoAutor);
            }
            
            JOptionPane.showMessageDialog(null, "Conta criada com sucesso");
            
            this.setVisible(false);
        }
    }//GEN-LAST:event_btCriarActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        
        this.setVisible(false);
        
    }//GEN-LAST:event_btVoltarActionPerformed

    private void rbtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNovaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNovaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNovaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNovaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaNovaConta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCriar;
    private javax.swing.JButton btVoltar;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JRadioButton rbtAutor;
    private javax.swing.JRadioButton rbtCliente;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
